### ISSUE TITLE
Merge mutagenwrapper with mutagen

### ISSUE THREAD

**Issue by jgandert** [clee704/mutagenwrapper#1]
This is just a suggestion, but maybe you'd like to help include (something like or) this in mutagen as there is an [open enhancement report](https://bitbucket.org/lazka/mutagen/issue/186/add-format-agnostic-common-tagging) on the mutagen repository for what you were trying to achieve with mutagenwrapper.

**Comment by clee704** [comment]
I'd like to contribute, but I don't have much time these days... I'll leave a comment on that issue.

**Comment by jgandert** [comment]
Nice :smiley:, thanks! :+1:
